watch_dir=/home/user/work/par2/sender/send
tmp_dir=/home/user/work/par2/sender/tmp
log_file=/home/user/work/par2/sender/log/sender.log

remote_host=192.168.1.12
remote_port=5001
remote_port_base=5000

total_parts=5
required_parts=3
